version: '3.7'

services:
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: postgres

    app:
      image: html-server-image:v1
      restart: always
      ports:
        - 800:80
      # volumes:
      #   - type: volume
      #     source: $HOME/ricethings-website/docs
      #     volume:
      #       nocopy: true
      
volumes:
  web_data:
    external: true

