version: '3.7'

services:
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5431:5432"        

    nginx:
      image: html-server-image:v1
      restart: always
      ports:
        - 800:80
      volumes:
        - $HOME/ricethings-website/docs:/docs
      
# volumes:
#   docs:

