version: '3'

services:
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: postgres

    html-server:
      image: html-server-image:v1
      restart: always
      ports:
        - 800:80

